//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ManualCustomerNotes
    {
        public long ID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<long> ManualCustomerID { get; set; }
        public Nullable<int> CustomerType { get; set; }
    
        public virtual tbl_ManualCustomers tbl_ManualCustomers { get; set; }
    }
}
