//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.tbl_Jobs = new HashSet<tbl_Jobs>();
            this.tbl_Referal = new HashSet<tbl_Referal>();
            this.tbl_User_City_Mapping = new HashSet<tbl_User_City_Mapping>();
            this.tbl_User_SubCategory_Mapping = new HashSet<tbl_User_SubCategory_Mapping>();
            this.tbl_UserImages = new HashSet<tbl_UserImages>();
            this.tbl_UserDevices = new HashSet<tbl_UserDevices>();
            this.tbl_Quotes = new HashSet<tbl_Quotes>();
            this.tbl_Appointments = new HashSet<tbl_Appointments>();
            this.tbl_Favorite = new HashSet<tbl_Favorite>();
            this.tbl_Flag = new HashSet<tbl_Flag>();
            this.tbl_Messages = new HashSet<tbl_Messages>();
            this.tbl_ThreadParticipants = new HashSet<tbl_ThreadParticipants>();
            this.tbl_NotificationSettings = new HashSet<tbl_NotificationSettings>();
            this.tbl_AppFeedBack = new HashSet<tbl_AppFeedBack>();
            this.tbl_ManualCustomers = new HashSet<tbl_ManualCustomers>();
        }
    
        public long Id { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<long> CityId { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> ZipId { get; set; }
        public string CompanyName { get; set; }
        public string Website { get; set; }
        public string StreetAddress { get; set; }
        public string Appartment { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsApprovedByAdmin { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<long> Type { get; set; }
        public Nullable<long> RoleId { get; set; }
        public string UniqueId { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<long> CountryCode { get; set; }
        public string Image { get; set; }
        public string ProfileUrl { get; set; }
        public string Platform { get; set; }
        public string DeviceToken { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> IsProfileUpdated { get; set; }
        public string AzureNotificationId { get; set; }
        public Nullable<bool> CanSendPushNotification { get; set; }
        public Nullable<int> SocialType { get; set; }
        public string SocialID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Jobs> tbl_Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Referal> tbl_Referal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_User_City_Mapping> tbl_User_City_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_User_SubCategory_Mapping> tbl_User_SubCategory_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserImages> tbl_UserImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserDevices> tbl_UserDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Quotes> tbl_Quotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Appointments> tbl_Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Favorite> tbl_Favorite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Flag> tbl_Flag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Messages> tbl_Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ThreadParticipants> tbl_ThreadParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_NotificationSettings> tbl_NotificationSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AppFeedBack> tbl_AppFeedBack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ManualCustomers> tbl_ManualCustomers { get; set; }
    }
}
