//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserDevices
    {
        public long ID { get; set; }
        public string DeviceToken { get; set; }
        public string Platform { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> LoggedOn { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
    }
}
