//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Flag
    {
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> FlagTypeID { get; set; }
        public Nullable<int> FlagType { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public string FlagReason { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
    }
}
