//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Appointments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Appointments()
        {
            this.tbl_AppointmentDates = new HashSet<tbl_AppointmentDates>();
        }
    
        public long ID { get; set; }
        public string Message { get; set; }
        public Nullable<long> QuoteID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<bool> IsAcceptedByProfessional { get; set; }
        public Nullable<long> ProfessionalID { get; set; }
        public Nullable<bool> IsRescheduled { get; set; }
        public Nullable<bool> RescheduledByUser { get; set; }
        public Nullable<bool> RescheduledByProfessional { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<bool> IsViewed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AppointmentDates> tbl_AppointmentDates { get; set; }
        public virtual tbl_Quotes tbl_Quotes { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
