//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ManualCustomers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ManualCustomers()
        {
            this.tbl_ManualCustomerNotes = new HashSet<tbl_ManualCustomerNotes>();
        }
    
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string StreetAddress { get; set; }
        public string Apartment { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<System.DateTime> addedon { get; set; }
        public string CountryCode { get; set; }
    
        public virtual tbl_State tbl_State { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ManualCustomerNotes> tbl_ManualCustomerNotes { get; set; }
    }
}
