//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Quotes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Quotes()
        {
            this.tbl_Appointments = new HashSet<tbl_Appointments>();
        }
    
        public long ID { get; set; }
        public Nullable<long> JobID { get; set; }
        public Nullable<long> ProfessionalID { get; set; }
        public Nullable<decimal> Estimate { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsViewed { get; set; }
    
        public virtual tbl_Jobs tbl_Jobs { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Appointments> tbl_Appointments { get; set; }
    }
}
