//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AppointmentDates
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> AppointmentDateTime { get; set; }
        public Nullable<long> AppointmentID { get; set; }
        public Nullable<bool> IsAcceptedByUser { get; set; }
        public Nullable<bool> IsAcceptedByProfessional { get; set; }
    
        public virtual tbl_Appointments tbl_Appointments { get; set; }
    }
}
